default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: taskmanager_backend_development

test:
  <<: *default
  database: taskmanager_backend_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cable:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV["DATABASE_URL"] %>

queue:
    adapter: postgresql
    encoding: unicode