default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: taskmanager_backend_development

test:
  <<: *default
  database: taskmanager_backend_test

production:
primary: &primary_production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cache:
     <<: *primary_production
     database: taskmanager_backend_production_cache
     migrations_paths: db/cache_migrate

queue:
     <<: *primary_production
     database: taskmanager_backend_production_queue
     migrations_paths: db/queue_migrate

cable:
     <<: *primary_production
     database: taskmanager_backend_production_cable
     migrations_paths: db/cable_migrate